import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="flexCenter">
      <body className="max-w-[450px] w-full h-svh bg-blue-50">{children}</body>
    </html>
  );
}
